### ISSUE TITLE
Status on support with nvim-treesitter

### ISSUE THREAD

**Issue by niklaswimmer** [IndianBoy42/tree-sitter-just#18]
What is the status on the PR mentioned in the readme? I am curious what it would take to support installing this grammar with `TSInstall` :)

**Comment by IndianBoy42** [comment]
Sorry I haven't touched this project in a really long time. I haven't opened any PR because this grammar is just not that good. I remember it misparses a LOT of reasonable code. Mostly due to janky handling of indents and dedents. The whole scanner probably should be rewritten, and then the grammer itself cleaned up based on that. There is a vim-just plugin that provides plain old vim syntax highlighting which is probably good enough for everyone. The only real reason for treesitter is probably to do injections, which doesn't work rn

**Comment by Hubro** [comment]
@IndianBoy42 / @niklaswimmer

FYI I have a PR open to add this parser to nvim-treesitter, marked as experimental. I fixed the injections query and improved the highlights a little (I think).

https://github.com/nvim-treesitter/nvim-treesitter/pull/5696

**Comment by tgross35** [comment]
@Hubro are you interested in waking up that PR? The project isn't perfect yet but should be much better than it was, and incremental updates should be easier once it is in the TS repo.

The queries in `queries/just` should work for TS. If they don't it would be great to get them fixed upstream too (I'll help with this if needed since they are autogenerated). Would be great to have some query review there anyway.

**Comment by Hubro** [comment]
@tgross35 Yep, I've been meaning to do it, I'm just waiting for some free time :smile: Perhaps this weekend.

**Comment by tgross35** [comment]
That's great news :) let me know if you need any help

**Comment by Hubro** [comment]
Opened new PR: https://github.com/nvim-treesitter/nvim-treesitter/pull/6245

I decided to not use the queries from this repo, since they are auto-generated and nvim-treesitter is really strict about style and conventions.

There were also some injection and highlight captures I was missing from the auto-generated queries.

**Comment by tgross35** [comment]
Great, thank you :)

I really would prefer to keep the queries in sync with this repo, the autogeneration should just be changing capture flavors. I'll follow up on that PR though

**Comment by tgross35** [comment]
Thanks to great work by @Hubro, the Just grammar is now included in nvim-treesitter! 🎉 🎉
